### ISSUE TITLE
profileUpdatePage Error

### ISSUE THREAD

**Issue by kavindu919** [safak/full-stack-estate#2]
**after creating profile update page this errors occurred in web page and console how can we fix it**  

Unexpected Application Error!
Objects are not valid as a React child (found: object with keys {message, name, code, config, request, response}). If you meant to render a collection of children, use an array instead.
Error: Objects are not valid as a React child (found: object with keys {message, name, code, config, request, response}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (http://localhost:5173/node_modules/.vite/deps/chunk-XBHG3ID7.js?v=12ed7edd:11222:17)
    at reconcileChildFibers2 (http://localhost:5173/node_modules/.vite/deps/chunk-XBHG3ID7.js?v=12ed7edd:11852:15)
    at reconcileChildren (http://localhost:5173/node_modules/.vite/deps/chunk-XBHG3ID7.js?v=12ed7edd:14292:37)
    at updateHostComponent (http://localhost:5173/node_modules/.vite/deps/chunk-XBHG3ID7.js?v=12ed7edd:14802:11)
    at beginWork (http://localhost:5173/node_modules/.vite/deps/chunk-XBHG3ID7.js?v=12ed7edd:15923:22)
    at beginWork$1 (http://localhost:5173/node_modules/.vite/deps/chunk-XBHG3ID7.js?v=12ed7edd:19749:22)
    at performUnitOfWork (http://localhost:5173/node_modules/.vite/deps/chunk-XBHG3ID7.js?v=12ed7edd:19194:20)
    at workLoopSync (http://localhost:5173/node_modules/.vite/deps/chunk-XBHG3ID7.js?v=12ed7edd:19133:13)
    at renderRootSync (http://localhost:5173/node_modules/.vite/deps/chunk-XBHG3ID7.js?v=12ed7edd:19112:15)
    at recoverFromConcurrentError (http://localhost:5173/node_modules/.vite/deps/chunk-XBHG3ID7.js?v=12ed7edd:18732:28)
    at performConcurrentWorkOnRoot (http://localhost:5173/node_modules/.vite/deps/chunk-XBHG3ID7.js?v=12ed7edd:18680:30)
    at workLoop (http://localhost:5173/node_modules/.vite/deps/chunk-XBHG3ID7.js?v=12ed7edd:197:42)
    at flushWork (http://localhost:5173/node_modules/.vite/deps/chunk-XBHG3ID7.js?v=12ed7edd:176:22)
    at MessagePort.performWorkUntilDeadline (http://localhost:5173/node_modules/.vite/deps/chunk-XBHG3ID7.js?v=12ed7edd:384:29)
**Here the error occur in console **
Argument `user` is missing.
    at Tn (C:\Users\Kavindu\Desktop\Push\api\node_modules\@prisma\client\runtime\library.js:115:6855)
    at In.handleRequestError (C:\Users\Kavindu\Desktop\Push\api\node_modules\@prisma\client\runtime\library.js:122:6510)
    at In.handleAndLogRequestError (C:\Users\Kavindu\Desktop\Push\api\node_modules\@prisma\client\runtime\library.js:122:6188)
    at In.request (C:\Users\Kavindu\Desktop\Push\api\node_modules\@prisma\client\runtime\library.js:122:5896)
    at async l (C:\Users\Kavindu\Desktop\Push\api\node_modules\@prisma\client\runtime\library.js:127:11167)
    at async addPost (file:///C:/Users/Kavindu/Desktop/Push/api/controllers/post.controller.js:44:21) {
  clientVersion: '5.13.0'
}

**Comment by V10codes** [comment]
did you fix this error?

**Comment by kavindu919** [comment]
unfortunately no.

**Comment by chandankumarm55** [comment]
you are trying to render the objects directly that's why  u are getting this error . it is happening in the api calling time and storing in state . make sure that your displaying the error message correctly . <div>{error}</div> incorrect method , <div>{error.message}</div> this method is correct

**Comment by kavindu919** [comment]
Thank you for the solution. i fixed my using this now its working properly
