### ISSUE TITLE
post creation error

### ISSUE THREAD

**Issue by dev-shreyash** [safak/full-stack-estate#3]
Argument `user` is missing. error affecting only when using client side software, when using api handling software Postman post was created successfully

PrismaClientValidationError: 
Invalid `prisma.post.create()` invocation:

{
  data: {
    title: "topi",
    price: 595,
    address: "gopi",
    city: "bbuyy",
    bedroom: null,
    bathroom: null,
    type: "rent",
    property: "apartment",
    latitude: "Nihil gloriosis solum extremo",
    longitude: "Expectant solvantur antiquis sentiant",
    images: [
      "https://res.cloudinary.com/shreyash-cloudinary/image/upload/v1714644668/posts/bdml2i788ltutawhuoff.jpg",
      "https://res.cloudinary.com/shreyash-cloudinary/image/upload/v1714644669/posts/x4h0ryoxp1wlfqmqgq8h.jpg",
      "https://res.cloudinary.com/shreyash-cloudinary/image/upload/v1714644669/posts/ear2u64cifehvcqdarf8.jpg",
      "https://res.cloudinary.com/shreyash-cloudinary/image/upload/v1714644671/posts/tbypzq9tioysgcca5kup.jpg"
    ],
    userId: "663218604260a76920dd4c9b",  
    postDetail: {
      create: {
        desc: "<p>lorem ispum</p>",      
        utilities: "owner",
        pet: "allowed",
        income: "Mundi amarissimam didicisset eripuit",
        size: 3979,
        school: 5491,
        bus: 2234,
        restaurant: 7662
      }
    },
+   user: {
+     create: UserCreateWithoutPostInput | UserUncheckedCreateWithoutPostInput,   
+     connectOrCreate: UserCreateOrConnectWithoutPostInput,
+     connect: UserWhereUniqueInput      
+   }
  }
}

Argument `user` is missing.
    at Tn (C:\Users\Shreyash1\Desktop\real-estate-react-project\api\node_modules\@prisma\client\runtime\library.js:115:6855)
    at In.handleRequestError (C:\Users\Shreyash1\Desktop\real-estate-react-project\api\node_modules\@prisma\client\runtime\library.js:122:6510)
    at In.handleAndLogRequestError (C:\Users\Shreyash1\Desktop\real-estate-react-project\api\node_modules\@prisma\client\runtime\library.js:122:6188)
    at In.request (C:\Users\Shreyash1\Desktop\real-estate-react-project\api\node_modules\@prisma\client\runtime\library.js:122:5896)
    at async l (C:\Users\Shreyash1\Desktop\real-estate-react-project\api\node_modules\@prisma\client\runtime\library.js:127:11167)
    at async addPost (file:///C:/Users/Shreyash1/Desktop/real-estate-react-project/api/controllers/post.controller.js:67:25) {
  clientVersion: '5.13.0'
}
[nodemon] restarting due to changes...
[nodemon] starting `node api/app.js app.js`
test
server is running on port 5000
PrismaClientValidationError: 
Invalid `prisma.post.create()` invocation:

{
  data: {
    title: "topi house",
    price: 595,
    address: "gopi",
    city: "mars",
    bedroom: 1,
    bathroom: 1,
    type: "rent",
    property: "apartment",
    latitude: "83787533",
    longitude: "36346433",
    images: [
      "https://res.cloudinary.com/shreyash-cloudinary/image/upload/v1714644668/posts/bdml2i788ltutawhuoff.jpg",
      "https://res.cloudinary.com/shreyash-cloudinary/image/upload/v1714644669/posts/x4h0ryoxp1wlfqmqgq8h.jpg",
      "https://res.cloudinary.com/shreyash-cloudinary/image/upload/v1714644669/posts/ear2u64cifehvcqdarf8.jpg",
      "https://res.cloudinary.com/shreyash-cloudinary/image/upload/v1714644671/posts/tbypzq9tioysgcca5kup.jpg"
    ],
    userId: "663218604260a76920dd4c9b",  
    postDetail: {
      create: {
        desc: "<p>lorem ispum</p>",      
        utilities: "owner",
        pet: "allowed",
        income: "Mundi amarissimam didicisset eripuit",
        size: 3979,
        school: 5491,
        bus: 2234,
        restaurant: 7662
      }
    },
+   user: {
+     create: UserCreateWithoutPostInput | UserUncheckedCreateWithoutPostInput,   
+     connectOrCreate: UserCreateOrConnectWithoutPostInput,
+     connect: UserWhereUniqueInput      
+   }
  }
}

Argument `user` is missing.
    at Tn (C:\Users\Shreyash1\Desktop\real-estate-react-project\api\node_modules\@prisma\client\runtime\library.js:115:6855)
    at In.handleRequestError (C:\Users\Shreyash1\Desktop\real-estate-react-project\api\node_modules\@prisma\client\runtime\library.js:122:6510)
    at In.handleAndLogRequestError (C:\Users\Shreyash1\Desktop\real-estate-react-project\api\node_modules\@prisma\client\runtime\library.js:122:6188)
    at In.request (C:\Users\Shreyash1\Desktop\real-estate-react-project\api\node_modules\@prisma\client\runtime\library.js:122:5896)
    at async l (C:\Users\Shreyash1\Desktop\real-estate-react-project\api\node_modules\@prisma\client\runtime\library.js:127:11167)
    at async addPost (file:///C:/Users/Shreyash1/Desktop/real-estate-react-project/api/controllers/post.controller.js:66:25) {
  clientVersion: '5.13.0'
}

**Comment by Akasshhhh** [comment]
hey bro can you let me know how did you fix it?
